# Generated by Django 5.0.1 on 2024-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_phone', models.CharField(max_length=30)),
                ('cust_address', models.CharField(max_length=300)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
    ]
