# Generated by Django 5.0.1 on 2024-03-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
