# Generated by Django 5.0.1 on 2024-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customers_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user_image',
            field=models.ImageField(default='None', upload_to='Customers'),
        ),
    ]
